model:
  packageName: "model"
  modelName: "userModel"
  fields: # 需要生成的model的字段
    - name: "UserName"
      type: "string"
      tag: "`json:\"user_name\"`"
      comment: "用户名"
    - name: "Mobile"
      type: "string"
      tag: "`json:\"mobile\"`"
      comment: "手机号"

excel:
  packageName: "excel"
  sheetName: "sheet1"
  name: "userExport"
  model:
    packageName: "model"
    name: "UserModel"
    headers: # 表头 
      - 
        - "用户名" 
        - "手机号"
    mergeHeaders: # 合并单元格
      - "A1:B1"
    fields: # 需要导出的字段
        - "UserName" 
        - "Mobile"
         